#!/bin/sh

lb config noauto --clean \
    --binary-images iso \
    --architectures amd64  \
    --distribution stretch \
    --archive-areas "main contrib non-free" \
    --iso-publisher "The Resilient Linux Team" \
    --iso-preparer "The Resilient Linux Team" \
    --iso-volume "Resilient Linux" \
    --iso-application "Resilient Linux" \
    --firmware-chroot false \
    --initsystem "systemd" \
    --security true \
    --apt-indices true \
    --source false \
    --debian-installer false \
    --memtest none \
    --win32-loader false \
    "${@}"

